import { readRofiColors } from './rofiColors.jsx';

// Ported from the hand-written ~/.config/rofi/recent-files.rasi (used by
// ~/.config/i3/rofi_recent_files.sh's fullscreen grid + preview mode).
// Written as a plain JS template literal, not through tauler-configgen's
// schema/codegen system: this file's `fullscreen`/`orientation`/`flow`/
// `fixed-columns`/`horizontal-align`/`calc()`/`@media` constructs are all
// one-offs not reused anywhere else in the shipped rofi-full-theme schema,
// so extending that schema for them would add generality nothing else
// needs — the same "manually written string template is the only
// format-specific surface" design this whole system already allows for.
const RecentFilesTheme = ConfigFile({
  path: '~/.config/rofi/recent-files.rasi',
  render: () => {
    const colors = readRofiColors();
    return `/* GENERATED by tauler from RecentFilesTheme.jsx — do not edit by
 * hand, edit ~/.config/tauler/layout.op.mdx instead. Fullscreen grid +
 * side preview, themed to match the kitty-synced palette used by the main
 * rofi theme. Used by ~/.config/i3/rofi_recent_files.sh. Preview pane
 * appears when launched with PREVIEW=true. */

* {
    font:             "JetBrains Mono 20";
    background-color: transparent;
    text-color:       ${colors.fg};
}

window {
    fullscreen:       true;
    background-color: ${colors.panel};
    padding:          2em;
    spacing:          1em;
    children:         [ wrap, listview-split ];
}

wrap {
    expand:      false;
    orientation: vertical;
    children:    [ inputbar, message ];
}

inputbar {
    padding:          10px 12px;
    spacing:          10px;
    background-color: ${colors.bg};
    border:           2px solid;
    border-color:     ${colors.accent};
    children:         [ prompt, entry ];
}

prompt {
    text-color: ${colors.accent};
}

entry {
    placeholder:       "search…";
    placeholder-color: ${colors["bg-alt-fg"]};
}

message {
    padding:          6px 8px;
    background-color: ${colors.bg};
}

listview-split {
    orientation: horizontal;
    spacing:     1em;
    children:    [ listview ];
}

listview {
    flow:          horizontal;
    fixed-columns: true;
    columns:       7;
    lines:         5;
    spacing:       0.6em;
    scrollbar:     false;
}

element {
    orientation:      vertical;
    padding:          0.4em;
    background-color: ${colors.bg};
    border:           2px solid;
    border-color:     transparent;
    children:         [ element-icon, element-text ];
}

element-icon {
    size:             calc(((100% - 8em) / 7));
    horizontal-align: 0.5;
    vertical-align:   0.5;
    background-color: transparent;
}

element-text {
    horizontal-align: 0.5;
    vertical-align:   0.5;
    padding:          0.3em 0 0 0;
    background-color: transparent;
    text-color:       inherit;
}

element selected {
    background-color: ${colors.bg};
    border-color:     ${colors.accent};
    text-color:       ${colors.accent};
}

/* PREVIEW=true: side-by-side layout with large preview of selected entry. */
@media ( enabled: env(PREVIEW, false)) {
    icon-current-entry {
        expand: true;
        size:   80%;
    }
    listview-split {
        children: [ listview, icon-current-entry ];
    }
    listview {
        columns: 4;
    }
}

@media ( enabled: env(NO_IMAGE, false)) {
    listview {
        columns: 1;
        spacing: 0.4em;
    }
    element {
        children: [ element-text ];
    }
    element-text {
        horizontal-align: 0.0;
    }
}
`;
  },
});

export default RecentFilesTheme;
